backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "businesses"
        label: "Businesses Directory"
        file: "businesses.json"
        fields:
          - label: "Businesses"
            name: "businesses"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Category", name: "category", widget: "select", options: ["Health & Beauty", "Food & Drinks", "Shopping", "Services", "Events", "Community", "Other"]}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Location", name: "location", widget: "string"}
              - {label: "Contact", name: "contact", widget: "string", required: false}
              - {label: "Source", name: "source", widget: "string", required: false}
              - {label: "Website", name: "website", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
